
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\doubled\rules\prefix\capitalized\numbers.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\doubled\doubled.dict
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\doubled\rules\prefix\upper\numbers.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\doubled\doubled.dict
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\doubled\rules\suffix\capitalized\numbers.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\doubled\doubled.dict
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\doubled\rules\suffix\upper\numbers.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\doubled\doubled.dict
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\common_rules\common.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\geonames\cities.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\common_rules\common.rules  D:\dictionary_brute\tests\test.txt D:\dictionary_brute\geonames\rus_cities_kbchange.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\common_rules\common.rules  D:\dictionary_brute\tests\test.txt D:\dictionary_brute\geonames\rus_cities_translit.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\common_rules\common.rules  D:\dictionary_brute\tests\test.txt D:\dictionary_brute\language\kb_change_rus
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\common_rules\common.rules  D:\dictionary_brute\tests\test.txt D:\dictionary_brute\language\translit_rus
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\common_rules\common.rules   D:\dictionary_brute\tests\test.txt D:\dictionary_brute\language\translit_rus
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\capitalized\1digit_or_2digits_month.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\capitalized\1digit_spec_char_month.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\capitalized\3digits_month.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\capitalized\4digits_month.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\capitalized\d_or_dd_month_yyyy.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\capitalized\d_or_dd_st_nd_rd_th_month.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\capitalized\dd_month.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\capitalized\dd_month_spec_char.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\capitalized\dd_month_yy.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\capitalized\ddmmyy_month.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\capitalized\ddyy_month.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\capitalized\month_4digits.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\capitalized\month_ddmmyy.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\capitalized\month_yy.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\capitalized\month_yy_spec_char.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\capitalized\month_yyyy.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\capitalized\spec_char_4digits_month.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\capitalized\spec_char_yy_month.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\capitalized\spec_char_yyyy_month.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\capitalized\yyyy_month.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\capitalized\yyyy_spec_char_month.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\lower\1digit_or_2digits_month.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\lower\1digit_spec_char_month.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\lower\3digits_month.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\lower\4digits_month.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\lower\d_or_dd_month_yyyy.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\lower\d_or_dd_st_nd_rd_th_month.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\lower\dd_month.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\lower\dd_month_spec_char.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\lower\dd_month_yy.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\lower\ddmmyy_month.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\lower\ddyy_month.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\lower\month_4digits.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\lower\month_ddmmyy.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\lower\month_yy.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\lower\month_yy_spec_char.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\lower\month_yyyy.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\lower\spec_char_4digits_month.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\lower\spec_char_yy_month.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\lower\spec_char_yyyy_month.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\lower\yyyy_month.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\lower\yyyy_spec_char_month.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\upper\1digit_or_2digits_month.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\upper\1digit_spec_char_month.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\upper\3digits_month.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\upper\4digits_month.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\upper\d_or_dd_month_yyyy.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\upper\d_or_dd_st_nd_rd_th_month.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\upper\dd_month.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\upper\dd_month_spec_char.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\upper\dd_month_yy.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\upper\ddmmyy_month.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\upper\ddyy_month.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\upper\month_4digits.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\upper\month_ddmmyy.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\upper\month_yy.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\upper\month_yy_spec_char.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\upper\month_yyyy.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\upper\spec_char_4digits_month.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\upper\spec_char_yy_month.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\upper\spec_char_yyyy_month.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\upper\yyyy_month.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\months\rules\upper\yyyy_spec_char_month.rule D:\dictionary_brute\tests\test.txt D:\dictionary_brute\months\months_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\prefix\capitalized\4digits_name\4digits_name.rules  D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\prefix\capitalized\spec_char_name_2digits_spec_char\spec_char_name_2digits_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\prefix\capitalized\spec_char_name_digit\spec_char_name_digit.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\prefix\capitalized\spec_char_name_mmdd_spec_char\spec_char_name_mmdd_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\prefix\capitalized\spec_char_name_yymm_spec_char\spec_char_name_yymm_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\prefix\capitalized\spec_char_name_yyyy\spec_char_name_yyyy.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\prefix\capitalized\spec_char_name_yyyy_spec_char\spec_char_name_yyyy_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\prefix\capitalized\yyyy_name\yyyy_name.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\prefix\capitalized\yyyy_name_spec_char\yyyy_name_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\prefix\capitalized\yyyy_spec_char_name\yyyy_spec_char_name.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\prefix\lower\4digits_name\4digits_name.rules  D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\prefix\lower\spec_char_name_2digits_spec_char\spec_char_name_2digits_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\prefix\lower\spec_char_name_digit\spec_char_name_digit.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\prefix\lower\spec_char_name_mmdd_spec_char\spec_char_name_mmdd_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\prefix\lower\spec_char_name_yymm_spec_char\spec_char_name_yymm_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\prefix\lower\spec_char_name_yyyy\spec_char_name_yyyy.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\prefix\lower\spec_char_name_yyyy_spec_char\spec_char_name_yyyy_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\prefix\lower\yyyy_name\yyyy_name.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\prefix\lower\yyyy_name_spec_char\yyyy_name_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\prefix\lower\yyyy_spec_char_name\yyyy_spec_char_name.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\suffix\capitalized\1_digit\1_digit.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\suffix\capitalized\2_digits\2_digits.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\suffix\capitalized\2_digits_spec_char\2_digits_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\suffix\capitalized\2_digits_spec_char_doubled\2_digits_spec_char_doubled.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\suffix\capitalized\3_digits\3_digits.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\suffix\capitalized\3_digits_spec_char\3_digits_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\suffix\capitalized\ddmm\ddmm.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\suffix\capitalized\ddmm_spec_char\ddmm_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\suffix\capitalized\ddmmyy\ddmmyy.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\suffix\capitalized\ddmmyyyy\ddmmyyyy.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\suffix\capitalized\ddyymm\ddyymm.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\suffix\capitalized\mmyy\mmyy.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\suffix\capitalized\mmyy_spec_char\mmyy_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\suffix\capitalized\popular_3_digits\popular_3_digits.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\suffix\capitalized\popular_4_digits\popular_4_digits.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\suffix\capitalized\spec_char_2_digits\spec_char_2_digits.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\suffix\capitalized\spec_char_doubled_2_digits\spec_char_doubled_2_digits.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\suffix\capitalized\spec_char_yyyy\spec_char_yyyy.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\suffix\capitalized\yyage\yyage.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\suffix\capitalized\yyage_spec_char\yyage_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\suffix\capitalized\yyyy_1000-1999\yyyy_1000-1999.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\suffix\capitalized\yyyy_1000-1999_spec_char\yyyy_1000-1999_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\suffix\capitalized\yyyy_1950-2030\yyyy_1950-2030.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\suffix\capitalized\yyyy_1950-2030_spec_char\yyyy_1950-2030_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\suffix\capitalized\yyyymm\yyyymm.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\suffix\lower\1_digit\1_digit.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\suffix\lower\2_digits\2_digits.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\suffix\lower\2_digits_spec_char\2_digits_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\suffix\lower\2_digits_spec_char_doubled\2_digits_spec_char_doubled.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\suffix\lower\3_digits\3_digits.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\suffix\lower\3_digits_spec_char\3_digits_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\suffix\lower\ddmm\ddmm.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\suffix\lower\ddmm_spec_char\ddmm_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\suffix\lower\ddmmyy\ddmmyy.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\suffix\lower\ddmmyyyy\ddmmyyyy.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\suffix\lower\ddyymm\ddyymm.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\suffix\lower\mmyy\mmyy.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\suffix\lower\mmyy_spec_char\mmyy_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\suffix\lower\popular_3_digits\popular_3_digits.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\suffix\lower\popular_4_digits\popular_4_digits.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\suffix\lower\spec_char_2_digits\spec_char_2_digits.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\suffix\lower\spec_char_doubled_2_digits\spec_char_doubled_2_digits.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\suffix\lower\spec_char_yyyy\spec_char_yyyy.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\suffix\lower\yyage\yyage.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\suffix\lower\yyage_spec_char\yyage_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\suffix\lower\yyyy_1000-1999\yyyy_1000-1999.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\suffix\lower\yyyy_1000-1999_spec_char\yyyy_1000-1999_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\suffix\lower\yyyy_1950-2030\yyyy_1950-2030.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\suffix\lower\yyyy_1950-2030_spec_char\yyyy_1950-2030_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\names\rules\suffix\lower\yyyymm\yyyymm.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\names\names_all.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\seasons\rules\prefix\capitalized\yyyy\yyyy_name.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\seasons\seasons.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\seasons\rules\prefix\capitalized\yyyy_password_spec_char\yyyy_name_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\seasons\seasons.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\seasons\rules\prefix\capitalized\yyyy_spec_char_password\yyyy_spec_char_name.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\seasons\seasons.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\seasons\rules\suffix\capitalized\1_digit\1_digit.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\seasons\seasons.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\seasons\rules\suffix\capitalized\2_digits\2_digits.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\seasons\seasons.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\seasons\rules\suffix\capitalized\2_digits_spec_char\2_digits_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\seasons\seasons.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\seasons\rules\suffix\capitalized\2_digits_spec_char_doubled\2_digits_spec_char_doubled.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\seasons\seasons.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\seasons\rules\suffix\capitalized\3_digits\3_digits.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\seasons\seasons.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\seasons\rules\suffix\capitalized\3_digits_spec_char\3_digits_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\seasons\seasons.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\seasons\rules\suffix\capitalized\popular_digits\popular_digits.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\seasons\seasons.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\seasons\rules\suffix\capitalized\spec_char_yyyy\spec_char_yyyy.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\seasons\seasons.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\seasons\rules\suffix\capitalized\yyyy_1950-2030\yyyy_1950-2030.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\seasons\seasons.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\seasons\rules\suffix\capitalized\yyyy_1950-2030_spec_char\yyyy_1950-2030_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\seasons\seasons.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\seasons\rules\prefix\capitalized\yyyy\yyyy_name.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\seasons\seasons_ru.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\seasons\rules\prefix\capitalized\yyyy_password_spec_char\yyyy_name_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\seasons\seasons_ru.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\seasons\rules\prefix\capitalized\yyyy_spec_char_password\yyyy_spec_char_name.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\seasons\seasons_ru.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\seasons\rules\suffix\capitalized\1_digit\1_digit.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\seasons\seasons_ru.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\seasons\rules\suffix\capitalized\2_digits\2_digits.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\seasons\seasons_ru.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\seasons\rules\suffix\capitalized\2_digits_spec_char\2_digits_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\seasons\seasons_ru.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\seasons\rules\suffix\capitalized\2_digits_spec_char_doubled\2_digits_spec_char_doubled.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\seasons\seasons_ru.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\seasons\rules\suffix\capitalized\3_digits\3_digits.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\seasons\seasons_ru.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\seasons\rules\suffix\capitalized\3_digits_spec_char\3_digits_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\seasons\seasons_ru.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\seasons\rules\suffix\capitalized\popular_digits\popular_digits.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\seasons\seasons_ru.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\seasons\rules\suffix\capitalized\spec_char_yyyy\spec_char_yyyy.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\seasons\seasons_ru.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\seasons\rules\suffix\capitalized\yyyy_1950-2030\yyyy_1950-2030.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\seasons\seasons_ru.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\seasons\rules\suffix\capitalized\yyyy_1950-2030_spec_char\yyyy_1950-2030_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\seasons\seasons_ru.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\prefix\capitalized\4digits_name\4digits_name.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\rus_surnames.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\prefix\capitalized\spec_char_name_2digits_spec_char\spec_char_name_2digits_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\rus_surnames.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\prefix\capitalized\spec_char_name_digit\spec_char_name_digit.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\rus_surnames.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\prefix\capitalized\spec_char_name_mmdd_spec_char\spec_char_name_mmdd_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\rus_surnames.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\prefix\capitalized\spec_char_name_yymm_spec_char\spec_char_name_yymm_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\rus_surnames.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\prefix\capitalized\spec_char_name_yyyy\spec_char_name_yyyy.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\rus_surnames.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\prefix\capitalized\spec_char_name_yyyy_spec_char\spec_char_name_yyyy_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\rus_surnames.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\prefix\capitalized\yyyy_name\yyyy_name.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\rus_surnames.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\prefix\capitalized\yyyy_name_spec_char\yyyy_name_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\rus_surnames.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\prefix\capitalized\yyyy_spec_char_name\yyyy_spec_char_name.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\rus_surnames.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\prefix\lower\4digits_name\4digits_name.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\rus_surnames.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\prefix\lower\spec_char_name_2digits_spec_char\spec_char_name_2digits_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\rus_surnames.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\prefix\lower\spec_char_name_digit\spec_char_name_digit.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\rus_surnames.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\prefix\lower\spec_char_name_mmdd_spec_char\spec_char_name_mmdd_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\rus_surnames.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\prefix\lower\spec_char_name_yymm_spec_char\spec_char_name_yymm_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\rus_surnames.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\prefix\lower\spec_char_name_yyyy\spec_char_name_yyyy.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\rus_surnames.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\prefix\lower\spec_char_name_yyyy_spec_char\spec_char_name_yyyy_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\rus_surnames.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\prefix\lower\yyyy_name\yyyy_name.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\rus_surnames.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\prefix\lower\yyyy_name_spec_char\yyyy_name_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\rus_surnames.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\prefix\lower\yyyy_spec_char_name\yyyy_spec_char_name.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\rus_surnames.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\suffix\capitalized\1_digit\1_digit.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\rus_surnames.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\suffix\capitalized\2_digits\2_digits.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\rus_surnames.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\suffix\capitalized\2_digits_spec_char\2_digits_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\rus_surnames.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\suffix\capitalized\3_digits\3_digits.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\rus_surnames.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\suffix\capitalized\3_digits_spec_char\3_digits_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\rus_surnames.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\suffix\capitalized\ddmm\ddmm.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\rus_surnames.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\suffix\capitalized\mmyy\mmyy.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\rus_surnames.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\suffix\capitalized\yyyy_1000-1999\yyyy_1000-1999.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\rus_surnames.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\suffix\capitalized\yyyy_1000-1999_spec_char\yyyy_1000-1999_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\rus_surnames.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\suffix\capitalized\yyyy_1950-2030\yyyy_1950-2030.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\rus_surnames.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\suffix\capitalized\yyyy_1950-2030_spec_char\yyyy_1950-2030_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\rus_surnames.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\suffix\lower\1_digit\1_digit.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\rus_surnames.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\suffix\lower\2_digits\2_digits.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\rus_surnames.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\suffix\lower\2_digits_spec_char\2_digits_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\rus_surnames.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\suffix\lower\3_digits\3_digits.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\rus_surnames.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\suffix\lower\3_digits_spec_char\3_digits_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\rus_surnames.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\suffix\lower\ddmm\ddmm.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\rus_surnames.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\suffix\lower\mmyy\mmyy.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\rus_surnames.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\suffix\lower\yyyy_1000-1999\yyyy_1000-1999.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\rus_surnames.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\suffix\lower\yyyy_1000-1999_spec_char\yyyy_1000-1999_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\rus_surnames.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\suffix\lower\yyyy_1950-2030\yyyy_1950-2030.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\rus_surnames.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\suffix\lower\yyyy_1950-2030_spec_char\yyyy_1950-2030_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\rus_surnames.txt
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\prefix\capitalized\4digits_name\4digits_name.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\surnames.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\prefix\capitalized\spec_char_name_2digits_spec_char\spec_char_name_2digits_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\surnames.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\prefix\capitalized\spec_char_name_digit\spec_char_name_digit.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\surnames.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\prefix\capitalized\spec_char_name_mmdd_spec_char\spec_char_name_mmdd_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\surnames.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\prefix\capitalized\spec_char_name_yymm_spec_char\spec_char_name_yymm_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\surnames.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\prefix\capitalized\spec_char_name_yyyy\spec_char_name_yyyy.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\surnames.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\prefix\capitalized\spec_char_name_yyyy_spec_char\spec_char_name_yyyy_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\surnames.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\prefix\capitalized\yyyy_name\yyyy_name.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\surnames.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\prefix\capitalized\yyyy_name_spec_char\yyyy_name_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\surnames.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\prefix\capitalized\yyyy_spec_char_name\yyyy_spec_char_name.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\surnames.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\prefix\lower\4digits_name\4digits_name.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\surnames.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\prefix\lower\spec_char_name_2digits_spec_char\spec_char_name_2digits_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\surnames.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\prefix\lower\spec_char_name_digit\spec_char_name_digit.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\surnames.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\prefix\lower\spec_char_name_mmdd_spec_char\spec_char_name_mmdd_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\surnames.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\prefix\lower\spec_char_name_yymm_spec_char\spec_char_name_yymm_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\surnames.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\prefix\lower\spec_char_name_yyyy\spec_char_name_yyyy.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\surnames.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\prefix\lower\spec_char_name_yyyy_spec_char\spec_char_name_yyyy_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\surnames.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\prefix\lower\yyyy_name\yyyy_name.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\surnames.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\prefix\lower\yyyy_name_spec_char\yyyy_name_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\surnames.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\prefix\lower\yyyy_spec_char_name\yyyy_spec_char_name.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\surnames.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\suffix\capitalized\1_digit\1_digit.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\surnames.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\suffix\capitalized\2_digits\2_digits.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\surnames.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\suffix\capitalized\2_digits_spec_char\2_digits_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\surnames.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\suffix\capitalized\3_digits\3_digits.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\surnames.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\suffix\capitalized\3_digits_spec_char\3_digits_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\surnames.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\suffix\capitalized\ddmm\ddmm.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\surnames.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\suffix\capitalized\mmyy\mmyy.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\surnames.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\suffix\capitalized\yyyy_1000-1999\yyyy_1000-1999.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\surnames.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\suffix\capitalized\yyyy_1000-1999_spec_char\yyyy_1000-1999_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\surnames.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\suffix\capitalized\yyyy_1950-2030\yyyy_1950-2030.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\surnames.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\suffix\capitalized\yyyy_1950-2030_spec_char\yyyy_1950-2030_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\surnames.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\suffix\lower\1_digit\1_digit.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\surnames.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\suffix\lower\2_digits\2_digits.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\surnames.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\suffix\lower\2_digits_spec_char\2_digits_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\surnames.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\suffix\lower\3_digits\3_digits.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\surnames.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\suffix\lower\3_digits_spec_char\3_digits_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\surnames.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\suffix\lower\ddmm\ddmm.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\surnames.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\suffix\lower\mmyy\mmyy.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\surnames.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\suffix\lower\yyyy_1000-1999\yyyy_1000-1999.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\surnames.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\suffix\lower\yyyy_1000-1999_spec_char\yyyy_1000-1999_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\surnames.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\suffix\lower\yyyy_1950-2030\yyyy_1950-2030.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\surnames.dic
D:\hashcat\hashcat-cli64.exe -m 0  -r D:\dictionary_brute\surnames\rules\suffix\lower\yyyy_1950-2030_spec_char\yyyy_1950-2030_spec_char.rules D:\dictionary_brute\tests\test.txt D:\dictionary_brute\surnames\surnames.dic
D:\hashcat\hashcat-cli64.exe -m 0   D:\dictionary_brute\tests\test.txt D:\dictionary_brute\tripple\tripple.dict